title: Disen Bygg
email: kontakt@disenbygg.no
phone: 905 61 296
address: Kolderups vei 2A, 0587 Oslo
description: >-
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, ex, recusandae. Facere modi sunt, quod quibusdam.
baseurl: ""
url: "http://disenbygg.no"

legalName: DISEN BYGG AS
orgNr: 997 979 230

# Sosial media
facebook_username: disenbygg
google_plus_username: disenbygg
twitter_username: disenbygg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
