title: Disen Bygg
email: post@disenbygg.no
phone: 905 61 296
address: Kolderups vei 2A, 0587 Oslo
description: >-
  Disen Bygg er en byggentreprenør som utfører arbeider innen rehabilitering, velikehold og nybygg i Stor-Oslo området.
baseurl: ""
url: "http://disenbygg.no"

legalName: DISEN BYGG AS
orgNr: 997 979 230

# Sosial media
facebook_username: disenbygg
google_plus_username: disenbygg
twitter_username: disenbygg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
